### PR TITLE
ci: add docker and release workflows

### PR DESCRIPTION
**Pull request by joshuasing**
Add `docker` and `release` GitHub Actions workflows.

The Docker workflow will build and publish unstable images when a commit is pushed to the `hemi` branch.
The Release workflow will build and publish stable images when a tag is pushed to `hemilabs/op-geth` and will also create a GitHub release with an automatically generated changelog (using `.github/release.yml`).

### CODE REVIEW

**Comment by ClaytonNorthey92** [comment]
hey @joshuasing I think that we will need to update the `go.mod` file; as of now, it is still pointing to a (via `replace`) "local" heminetwork directory, but can be changed to point to a remote one.  We should update this, so we don't have to keep a heminetwork directory wherever we build.

**Review by jcvernaleo — APPROVED** [review]
OK

**Comment by ClaytonNorthey92** [comment]
hey @joshuasing , I ran the `docker build .` on the latest, I am getting this error.  I think we should update the Go base image.  what do you think?
```
 > [builder 5/7] RUN cd /go-ethereum && go mod download:                                                                                                                    
0.713 go: go.mod requires go >= 1.22.2 (running go 1.21.10; GOTOOLCHAIN=local) 
```

**Comment by joshuasing** [comment]
> hey @joshuasing , I ran the `docker build .` on the latest, I am getting this error. I think we should update the Go base image. what do you think?
> 
> ```
>  > [builder 5/7] RUN cd /go-ethereum && go mod download:                                                                                                                    
> 0.713 go: go.mod requires go >= 1.22.2 (running go 1.21.10; GOTOOLCHAIN=local) 
> ```

Oh, good catch! Yes, I will update the Go images and pin them to hashes.

**Review by jcvernaleo — APPROVED** [review]
docker container builds just fine for me.

OK

**Comment by ClaytonNorthey92** [comment]
thanks @joshuasing let's merge this; it's a bit difficult to test on localnet due to the way localnet is set up (i.e. the way it needs to create the genesis and rollup configs), but I don't see any issues with it.  we should merge, then connect with @dhidalgX to test on k8s testnet (i.e. use the release image in the config.)

**Review by ClaytonNorthey92 — APPROVED** [review]

**Pull request merged**
